apiVersion : apps/v1
kind: Deployment
metadata:
  name: ratingapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratingapi
  template:
    metadata:
      labels:
        app: ratingapi 
    spec:
      containers:
        - name: ratingapi 
          image: acrvod.azurecr.io/ratingapi
          ports:
          - containerPort: 80